- hosts: cloning
  collections:
    - smart.jcllib
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: create_jcl
      vars:
        jcllib: "{{ JCLLIB }}"
        jcl_name: chvname1.jcl
        member: CHVNAME1
        name: "{{ driver.mcat.name }}"
        iodf_suffix: A1
