- hosts: cloning
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: zos_cloning_jcl_create
      vars:
        jcl_name: chvname1.jcl
        member: CHVNAME1
        name: "{{ driver.mcat.name }}"
        iodf_suffix: A1
