- hosts: cloning
  collections:
    - smart.jcllib
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: create_jcl
      vars:
        jcllib: "{{ JCLLIB }}"
        jcl_name: defiptx1.jcl
        member: DEFIPTX1
        volume: F21DT1
