- hosts: cloning
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: zos_cloning_jcl_create
      vars:
        jcl_name: defmcat1.jcl
        member: DEFMCAT1
        name: "{{ target.mcat.name }}"
        volume: "{{ target.mcat.volume }}"
