- hosts: cloning
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: zos_cloning_jcl_create
      vars: 
        jcl_name: dsslcpy1.jcl
        member: DSSLCPY1
        target_volume: "{{ target.volumes[0] }}"
        source_volume: "{{ source.volumes[0] }}"
