- hosts: cloning
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: zos_cloning_jcl_create
      vars:
        jcl_name: dsslcpy1.jcl
        member: DSSLCPY2
        target_volume: "{{ target.volumes[1] }}"
        source_volume: "{{ source.volumes[1] }}"
