- hosts: cloning
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: zos_cloning_jcl_create
      vars:
        jcl_name: expdct02.jcl
        member: EXPDCT02
        name: "{{ driver.mcat.name }}"
        volume: "{{ driver.mcat.name }}"
