- hosts: cloning
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: zos_cloning_jcl_create
      vars:
        jcl_name: expdsc01.jcl
        member: EXPDSC01
