- hosts: cloning
  collections:
    - smart.jcllib
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - include_role:
        name: create_jcl
      vars:
        jcllib: "{{ JCLLIB }}"
        jcl_name: impcon01.jcl
        member: IMPCON01
        name: "{{ driver.mcat.name }}"
        volume: "{{ driver.mcat.volume }}" 
