- name: set fact jcl_path for use
  set_fact:
    jcl_path: "/tmp/{{ jcl_name }}_{{ member }}"

- name: delete an old JCL
  file:
    path: "{{ jcl_path }}"
    state: absent

- name: create a JCL
  template:
    src: "{{ jcl_name }}.j2"
    dest: "{{ jcl_path }}"

- name: Convert the file from ISO8859-1 to IBM-1047
  zos_encode:
    src: "{{ jcl_path }}"
    from_encoding: ISO8859-1
    to_encoding: IBM-1047

- name: retrieve the content of the JCL
  shell: cat "{{ jcl_path }}"
  register: content

- name: show the content
  debug:
    msg: "{{ content.stdout_lines }}"

- name: Copy the file to MVS Dataset
  shell: cp "{{ jcl_path }}" "//'{{ jcllib|upper }}({{ member|upper }})'"
