- debug:
    msg: "{{ jcl_name }}"

- name: create a JCL
  template:
    src: "{{ jcl_name }}.j2"
    dest: "/tmp/{{ jcl_name }}"
  register: result

- name: Convert the file from ISO8859-1 to IBM-1047
  zos_encode:
    src: "{{ tgt_tmp_dir }}/{{ jcl_name }}"
    from_encoding: ISO8859-1
    to_encoding: IBM-1047
  when: result is changed

- name: Copy the file to MVS Dataset
  command: cp "{{ tgt_tmp_dir }}/{{ jcl_name }}" "//'{{ jcllib|upper }}({{ member|upper }})'"
